drop table if exists contacts;
create table contacts (
	id INT primary key,
	firstname VARCHAR(50),
	lastname VARCHAR(50),
	email VARCHAR(50) unique,
	gender VARCHAR(50),
	phone VARCHAR(50) unique,
	city VARCHAR(50),
	state VARCHAR(50),
	country VARCHAR(50),
	picture VARCHAR(255),
	dob DATE
);
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (1, 'Daffi', 'Musgrove', 'dmusgrove0@time.com', 'Female', '585-618-8458', 'Rochester', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/1.jpg', '1968/01/13');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (2, 'Hannie', 'Keyden', 'hkeyden1@yellowpages.com', 'Female', '678-480-8140', 'Decatur', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/2.jpg', '1961/09/20');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (3, 'Ximenes', 'Viant', 'xviant2@hexun.com', 'Male', '757-503-9164', 'Norfolk', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/3.jpg', '1953/09/27');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (4, 'Gates', 'Fairholm', 'gfairholm3@qq.com', 'Female', '484-432-1868', 'Bethlehem', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/4.jpg', '1981/05/20');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (5, 'Beilul', 'Flipsen', 'bflipsen4@ebay.com', 'Female', '253-636-1125', 'Tacoma', 'Washington', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/5.jpg', '1951/07/26');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (6, 'Shanna', 'McCreery', 'smccreery5@yellowpages.com', 'Female', '914-613-4621', 'Staten Island', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/6.jpg', '1981/08/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (7, 'Ursulina', 'Squirrel', 'usquirrel6@google.pl', 'Female', '502-715-4559', 'Louisville', 'Kentucky', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/7.jpg', '1984/02/16');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (8, 'Sybila', 'Faireclough', 'sfaireclough7@liveinternet.ru', 'Female', '719-999-1489', 'Pueblo', 'Colorado', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/8.jpg', '1966/10/19');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (9, 'Melita', 'Rawlin', 'mrawlin8@angelfire.com', 'Female', '585-348-7259', 'Rochester', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/9.jpg', '1976/09/23');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (10, 'Morey', 'Stephenson', 'mstephenson9@google.cn', 'Male', '615-618-9420', 'Memphis', 'Tennessee', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/10.jpg', '1966/11/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (11, 'Gordy', 'Chopy', 'gchopya@alexa.com', 'Male', '305-531-1297', 'Miami', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/11.jpg', '1990/01/20');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (12, 'Alf', 'Faloon', 'afaloonb@skyrock.com', 'Male', '917-152-7340', 'New York City', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/12.jpg', '1988/11/05');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (13, 'Carie', 'Harwin', 'charwinc@hud.gov', 'Female', '213-856-1374', 'Los Angeles', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/13.jpg', '1953/03/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (14, 'Nancie', 'Feuell', 'nfeuelld@ebay.com', 'Female', '202-110-9443', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/14.jpg', '1957/02/19');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (15, 'Maggi', 'Screas', 'mscrease@nbcnews.com', 'Female', '720-542-3863', 'Littleton', 'Colorado', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/15.jpg', '1953/04/13');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (16, 'Janek', 'Lote', 'jlotef@dailymail.co.uk', 'Male', '904-482-8002', 'Jacksonville', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/16.jpg', '1959/07/27');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (17, 'Brina', 'Obbard', 'bobbardg@washingtonpost.com', 'Female', '641-847-7022', 'Des Moines', 'Iowa', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/17.jpg', '1988/11/16');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (18, 'Kasey', 'Shippey', 'kshippeyh@jiathis.com', 'Female', '213-770-7337', 'Los Angeles', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/18.jpg', '1987/01/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (19, 'Kingsly', 'Gimert', 'kgimerti@cocolog-nifty.com', 'Male', '816-292-8114', 'Kansas City', 'Missouri', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/19.jpg', '1982/07/01');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (20, 'Iona', 'Lowings', 'ilowingsj@1688.com', 'Female', '484-586-5080', 'Valley Forge', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/20.jpg', '1985/07/28');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (21, 'Honey', 'Cod', 'hcodk@yahoo.com', 'Female', '806-263-1044', 'Lubbock', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/21.jpg', '1990/10/25');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (22, 'Reid', 'Garshore', 'rgarshorel@ovh.net', 'Male', '610-711-3379', 'Reading', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/22.jpg', '1961/08/04');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (23, 'Alice', 'Winkle', 'awinklem@ted.com', 'Female', '917-627-8028', 'Brooklyn', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/23.jpg', '1966/10/05');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (24, 'Ibrahim', 'Atto', 'iatton@reference.com', 'Male', '330-338-4492', 'Canton', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/24.jpg', '1982/10/14');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (25, 'Adriane', 'Philippsohn', 'aphilippsohno@wikipedia.org', 'Female', '505-998-2723', 'Albuquerque', 'New Mexico', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/25.jpg', '1970/11/28');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (26, 'Thurston', 'Frayne', 'tfraynep@myspace.com', 'Male', '757-945-3043', 'Richmond', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/26.jpg', '1994/04/24');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (27, 'Flss', 'Le Clercq', 'fleclercqq@pagesperso-orange.fr', 'Female', '574-110-5088', 'South Bend', 'Indiana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/27.jpg', '1984/03/19');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (28, 'Ailis', 'Boothby', 'aboothbyr@pbs.org', 'Female', '609-598-7819', 'Trenton', 'New Jersey', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/28.jpg', '1999/05/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (29, 'Kelsi', 'Leavold', 'kleavolds@google.co.uk', 'Female', '972-854-2333', 'Dallas', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/29.jpg', '1984/08/31');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (30, 'Winnah', 'Armall', 'warmallt@yellowpages.com', 'Female', '406-460-6917', 'Bozeman', 'Montana', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/30.jpg', '1952/11/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (31, 'Myrtice', 'Attril', 'mattrilu@unesco.org', 'Female', '404-315-1707', 'Atlanta', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/31.jpg', '1978/04/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (32, 'Igor', 'Eisig', 'ieisigv@csmonitor.com', 'Male', '205-959-3966', 'Birmingham', 'Alabama', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/32.jpg', '1959/01/31');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (33, 'Brandi', 'Sanchiz', 'bsanchizw@webmd.com', 'Female', '215-743-3472', 'Philadelphia', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/33.jpg', '1957/05/23');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (34, 'Dasya', 'Thay', 'dthayx@kickstarter.com', 'Female', '912-413-6182', 'Savannah', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/34.jpg', '1995/08/04');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (35, 'Dinny', 'Iacovolo', 'diacovoloy@usda.gov', 'Female', '440-810-8348', 'Cleveland', 'Ohio', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/35.jpg', '1978/05/07');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (36, 'Felita', 'Dulake', 'fdulakez@chicagotribune.com', 'Female', '806-842-8471', 'Lubbock', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/36.jpg', '1975/10/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (37, 'Verna', 'Bridell', 'vbridell10@goo.ne.jp', 'Female', '814-256-1698', 'Erie', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/37.jpg', '1998/05/02');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (38, 'Mannie', 'Cochrane', 'mcochrane11@dedecms.com', 'Male', '512-380-0456', 'Austin', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/38.jpg', '1958/10/25');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (39, 'Melinda', 'Kinze', 'mkinze12@statcounter.com', 'Female', '801-346-7589', 'Salt Lake City', 'Utah', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/39.jpg', '1961/05/25');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (40, 'Teri', 'Blanchflower', 'tblanchflower13@usnews.com', 'Female', '570-471-0723', 'Wilkes Barre', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/40.jpg', '1959/06/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (41, 'Regen', 'Mattke', 'rmattke14@china.com.cn', 'Male', '913-152-5469', 'Shawnee Mission', 'Kansas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/41.jpg', '1959/10/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (42, 'Blayne', 'Ruddiforth', 'bruddiforth15@reuters.com', 'Male', '928-643-1058', 'Peoria', 'Arizona', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/42.jpg', '1995/05/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (43, 'Fiorenze', 'Fowlds', 'ffowlds16@forbes.com', 'Female', '918-577-1914', 'Tulsa', 'Oklahoma', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/43.jpg', '1975/02/01');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (44, 'Bren', 'Cosker', 'bcosker17@mozilla.org', 'Female', '203-282-5942', 'Hartford', 'Connecticut', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/44.jpg', '1978/06/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (45, 'Eloisa', 'Oughtright', 'eoughtright18@cocolog-nifty.com', 'Female', '786-543-0659', 'Miami', 'Florida', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/45.jpg', '1955/03/20');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (46, 'Jeannine', 'Piccard', 'jpiccard19@shutterfly.com', 'Female', '714-224-4187', 'Irvine', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/46.jpg', '1976/02/10');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (47, 'Adam', 'Olivia', 'aolivia1a@vinaora.com', 'Male', '443-682-2060', 'Baltimore', 'Maryland', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/47.jpg', '1951/06/11');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (48, 'Mabelle', 'Cudbertson', 'mcudbertson1b@bluehost.com', 'Female', '918-156-2319', 'Tulsa', 'Oklahoma', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/48.jpg', '1971/03/13');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (49, 'Gustaf', 'Winsborrow', 'gwinsborrow1c@reference.com', 'Male', '712-943-0813', 'Omaha', 'Nebraska', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/49.jpg', '1987/01/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (50, 'Maxwell', 'Rawsen', 'mrawsen1d@mlb.com', 'Male', '770-101-0512', 'Decatur', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/50.jpg', '1998/12/14');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (51, 'Boycie', 'Bishop', 'bbishop1e@w3.org', 'Male', '217-188-5749', 'Decatur', 'Illinois', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/51.jpg', '1952/06/13');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (52, 'Vincenz', 'Saunder', 'vsaunder1f@symantec.com', 'Male', '757-239-2079', 'Richmond', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/52.jpg', '1998/01/31');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (53, 'Farly', 'Tarney', 'ftarney1g@mail.ru', 'Male', '916-912-7590', 'Sacramento', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/53.jpg', '1982/09/15');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (54, 'Rene', 'Boner', 'rboner1h@usda.gov', 'Male', '862-944-8882', 'Newark', 'New Jersey', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/54.jpg', '1998/12/24');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (55, 'Kristoffer', 'Sarge', 'ksarge1i@jugem.jp', 'Male', '408-498-4329', 'San Jose', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/55.jpg', '1969/02/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (56, 'Athene', 'Gwilym', 'agwilym1j@technorati.com', 'Female', '915-383-3317', 'El Paso', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/56.jpg', '1954/01/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (57, 'Jeffrey', 'Petruskevich', 'jpetruskevich1k@newyorker.com', 'Male', '615-876-5474', 'Nashville', 'Tennessee', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/57.jpg', '1967/09/27');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (58, 'Trever', 'Dell Casa', 'tdellcasa1l@samsung.com', 'Male', '973-105-1951', 'Newark', 'New Jersey', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/58.jpg', '1951/03/28');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (59, 'Otho', 'Golder', 'ogolder1m@freewebs.com', 'Male', '281-439-5533', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/59.jpg', '1982/08/11');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (60, 'Enrica', 'Honack', 'ehonack1n@ft.com', 'Female', '202-380-6295', 'Washington', 'District of Columbia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/60.jpg', '1993/01/20');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (61, 'Vita', 'Granger', 'vgranger1o@sciencedirect.com', 'Female', '562-380-8119', 'Long Beach', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/61.jpg', '1967/04/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (62, 'Hamilton', 'Snedden', 'hsnedden1p@mashable.com', 'Male', '313-438-2510', 'Detroit', 'Michigan', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/62.jpg', '1979/07/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (63, 'Napoleon', 'Kilfeder', 'nkilfeder1q@lulu.com', 'Male', '210-862-1920', 'San Antonio', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/63.jpg', '1955/01/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (64, 'Mohammed', 'Vampouille', 'mvampouille1r@umn.edu', 'Male', '860-789-5624', 'Hartford', 'Connecticut', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/64.jpg', '1968/03/31');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (65, 'Inigo', 'Hanford', 'ihanford1s@java.com', 'Male', '503-167-5678', 'Portland', 'Oregon', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/65.jpg', '1992/07/16');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (66, 'Derron', 'Ardling', 'dardling1t@uol.com.br', 'Male', '650-340-8159', 'Redwood City', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/66.jpg', '1971/02/05');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (67, 'Zora', 'Schrir', 'zschrir1u@bloglines.com', 'Female', '775-474-9598', 'Sparks', 'Nevada', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/67.jpg', '1992/07/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (68, 'Wood', 'Beedie', 'wbeedie1v@ucsd.edu', 'Male', '913-805-1640', 'Kansas City', 'Kansas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/68.jpg', '1999/09/13');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (69, 'Franky', 'Ponnsett', 'fponnsett1w@alexa.com', 'Female', '916-507-4321', 'Sacramento', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/69.jpg', '1958/06/29');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (70, 'Dacy', 'Trowle', 'dtrowle1x@hugedomains.com', 'Female', '571-773-8429', 'Springfield', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/70.jpg', '1994/02/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (71, 'Nappie', 'Wingate', 'nwingate1y@usa.gov', 'Male', '713-137-1010', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/71.jpg', '1960/04/18');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (72, 'Yvon', 'Sevier', 'ysevier1z@google.com.br', 'Male', '609-297-9509', 'Trenton', 'New Jersey', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/72.jpg', '1953/08/25');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (73, 'Ronni', 'Sweatman', 'rsweatman20@yahoo.com', 'Female', '215-237-6748', 'Philadelphia', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/73.jpg', '1952/11/22');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (74, 'Dare', 'Feldbrin', 'dfeldbrin21@oaic.gov.au', 'Male', '210-628-4121', 'San Antonio', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/74.jpg', '1970/08/28');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (75, 'Emilio', 'Nipper', 'enipper22@addthis.com', 'Male', '757-202-5911', 'Virginia Beach', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/75.jpg', '1955/07/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (76, 'Beck', 'Scolli', 'bscolli23@reuters.com', 'Male', '901-285-8498', 'Memphis', 'Tennessee', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/76.jpg', '1951/07/27');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (77, 'Bronson', 'Maddra', 'bmaddra24@example.com', 'Male', '562-636-2314', 'Anaheim', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/77.jpg', '1950/10/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (78, 'Teodor', 'Bettles', 'tbettles25@pagesperso-orange.fr', 'Male', '434-674-6929', 'Durham', 'North Carolina', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/78.jpg', '1962/05/04');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (79, 'Reginald', 'McCalister', 'rmccalister26@mashable.com', 'Male', '623-541-8557', 'Phoenix', 'Arizona', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/79.jpg', '1992/06/15');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (80, 'Marga', 'Domico', 'mdomico27@spiegel.de', 'Female', '706-505-9191', 'Columbus', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/80.jpg', '1951/08/15');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (81, 'Sherill', 'Varvell', 'svarvell28@who.int', 'Female', '585-372-3244', 'Rochester', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/81.jpg', '1976/05/08');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (82, 'Antone', 'Dearle', 'adearle29@blog.com', 'Male', '617-574-4330', 'Boston', 'Massachusetts', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/82.jpg', '1979/03/23');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (83, 'Markos', 'Kewley', 'mkewley2a@google.nl', 'Male', '571-451-3042', 'Falls Church', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/83.jpg', '1977/06/09');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (84, 'Joseph', 'MacFadzean', 'jmacfadzean2b@umn.edu', 'Male', '412-249-6196', 'Pittsburgh', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/84.jpg', '1966/12/05');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (85, 'Brook', 'Landeaux', 'blandeaux2c@google.com.hk', 'Female', '864-282-6601', 'Greenville', 'South Carolina', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/85.jpg', '1970/02/08');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (86, 'Emilee', 'Budden', 'ebudden2d@youku.com', 'Female', '713-210-4388', 'Houston', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/86.jpg', '1985/04/10');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (87, 'Brandyn', 'Chaperlin', 'bchaperlin2e@topsy.com', 'Male', '626-791-4668', 'Pasadena', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/87.jpg', '1994/09/09');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (88, 'Stephen', 'Soles', 'ssoles2f@networkadvertising.org', 'Male', '484-204-4799', 'Reading', 'Pennsylvania', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/88.jpg', '1982/01/17');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (89, 'Cris', 'Cornbill', 'ccornbill2g@prweb.com', 'Male', '704-380-9644', 'Charlotte', 'North Carolina', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/89.jpg', '1981/12/22');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (90, 'Lauraine', 'Abendroth', 'labendroth2h@csmonitor.com', 'Female', '678-854-8991', 'Marietta', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/90.jpg', '1987/12/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (91, 'Benedikta', 'Luckings', 'bluckings2i@amazon.co.jp', 'Female', '806-338-5284', 'Amarillo', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/91.jpg', '1987/03/30');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (92, 'Celeste', 'Vidgeon', 'cvidgeon2j@who.int', 'Female', '404-933-6638', 'Atlanta', 'Georgia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/92.jpg', '1976/12/09');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (93, 'Rusty', 'Shaw', 'rshaw2k@a8.net', 'Male', '901-894-4398', 'Memphis', 'Tennessee', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/93.jpg', '1972/11/06');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (94, 'Cord', 'Gate', 'cgate2l@oaic.gov.au', 'Male', '203-539-8195', 'Waterbury', 'Connecticut', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/94.jpg', '1968/03/03');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (95, 'Lewie', 'Fridd', 'lfridd2m@buzzfeed.com', 'Male', '254-434-5669', 'Waco', 'Texas', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/95.jpg', '1991/02/23');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (96, 'Suzie', 'Kindell', 'skindell2n@ning.com', 'Female', '714-232-4613', 'Garden Grove', 'California', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/96.jpg', '1951/11/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (97, 'Jude', 'Tarzey', 'jtarzey2o@ezinearticles.com', 'Male', '716-325-2677', 'Buffalo', 'New York', 'United States', 'http://kvinod.com/old_ci/randomdata/images/men/97.jpg', '2000/01/24');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (98, 'Roch', 'Bevens', 'rbevens2p@sciencedirect.com', 'Female', '712-425-8856', 'Sioux City', 'Iowa', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/98.jpg', '1992/10/26');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (99, 'Ilise', 'Lemonnier', 'ilemonnier2q@earthlink.net', 'Female', '757-225-4128', 'Norfolk', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/99.jpg', '1991/03/21');
insert into contacts (id, firstname, lastname, email, gender, phone, city, state, country, picture, dob) values (100, 'Ruperta', 'Maltby', 'rmaltby2r@amazon.co.jp', 'Female', '804-241-5994', 'Richmond', 'Virginia', 'United States', 'http://kvinod.com/old_ci/randomdata/images/women/100.jpg', '1962/10/19');
