package com.ps.web;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet("/print-table")
public class PrintTableServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) 
			throws ServletException, IOException {
		
		// typical workflow inside a servlet
		// 1 read any request parameters headers, cookies etc
		String input=request.getParameter("num");
		int num;
		try {
			num = Integer.parseInt(input);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			//response.sendError(HttpServletResponse.SC_BAD_REQUEST);
			response.sendRedirect("/app");
			return;
		}
		// 2 get data required for output(from model)
		// 3 generate the response content(html, generated by view/jsp)
		// 4 write the response
		StringBuilder sb=new StringBuilder();
		sb.append("<h3> Miltiplication Table for ")
			.append(num)
			.append(" : </h3>");
		
		for(int i=1;i<11;i++) {
			sb.append(num*i)
				.append("<br>");
		}
		
		response.setContentType("text/html");
		PrintWriter out = response.getWriter();
		out.println(sb.toString());
		out.close();
	}

	

}
